// Generated by Selenium IDE good code
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace Assignment4
{


    [TestFixture]
    public class DefaultSuiteTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void insuranceQuote2validdataAge25Experience3Accidents4()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            {
                var element = driver.FindElement(By.Id("firstName"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).ClickAndHold().Perform();
            }
            {
                var element = driver.FindElement(By.Id("firstName"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.Id("firstName"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Dikshu");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Rawat");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("qwertyu");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            {
                var element = driver.FindElement(By.Id("postalCode"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).ClickAndHold().Perform();
            }
            {
                var element = driver.FindElement(By.Id("postalCode"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.Id("postalCode"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).Click();
            {
                var element = driver.FindElement(By.Id("postalCode"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("111-111-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("adsbvd@dhbfjh.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("0");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$5500"));
            }
        }
        [Test]
        public void insuranceQuote1validdataAge24Experience3Accidents0()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Dikshu");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Rawat");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("resdtfgh");
            driver.FindElement(By.CssSelector(".form-row:nth-child(4)")).Click();
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.CssSelector(".form-row:nth-child(5)")).Click();
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("HFDGF@ffdhgf.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("35");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("9");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("2");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$3905"));
            }
        }
        [Test]
        public void insuranceQuote3validdataAge35Experience9Accidents2()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Dikshu");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Rawat");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("qwedfghj");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.CssSelector(".col-md-4:nth-child(1)")).Click();
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("QWER@mmm.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).Click();
            {
                var element = driver.FindElement(By.Id("age"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).ClickAndHold().Perform();
            }
            {
                var element = driver.FindElement(By.Id("age"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.Id("age"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("4");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
            }
        }
        [Test]
        public void insuranceQuote4InvalidphonenumberwithallremainingfieldswithvaliddataAge27Experience3Accidents0()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("qwrestd");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("sertdfgh");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("werstdfg");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("ersdtfgh");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-1234567");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("DSGDSG@ghf.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                var element = driver.FindElement(By.Id("btnSubmit"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.CssSelector(".col-md-4:nth-child(1) > label:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(4) > label")).Click();
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).Click();
            {
                var element = driver.FindElement(By.Id("phone"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.Id("phone")).Click();
            Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
        }
        [Test]
        public void insuranceQuote5InvalidemailaddresswithallremainingfieldswithvaliddataAge28Experience3Accidents0()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("fdgfdhhf");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("gfhgf");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("wedfg");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("HDF3.COM");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).Click();
            {
                var element = driver.FindElement(By.Id("email"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.Id("email")).Click();
            Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
        }
        [Test]
        public void insuranceQuote6InvalidpostalcodewithallremainingfieldswithvaliddataAge35Experience15Accidents1()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("erstdfh");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("essrdtfgv");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("erdtfyghjb");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("wertgyh");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("122-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("aresdfg@.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("35");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("15");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                var element = driver.FindElement(By.Id("btnSubmit"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("aresdfg@gggg.com");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
        }
        [Test]
        public void insuranceQuote7AgeomittedwithallremainingfieldswithvaliddataExperience5Accidents0()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("asdfgh");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("sdfgbn");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("sdfghbjn");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("SDFG@dfg.com");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                var element = driver.FindElement(By.Id("btnSubmit"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
        }
        [Test]
        public void insuranceQuote8NumberofatfaultaccidentsomittedwithallremainingfieldswithvaliddataAge37Experience8()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("sedrtfgh");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("wedrtfg");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("wsedrtfgyh");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.CssSelector(".col-md-4:nth-child(1)")).Click();
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("srdftgh@edfg.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("28");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("7");
            driver.FindElement(By.Id("experience")).SendKeys("6");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("experience")).SendKeys("6");
            driver.FindElement(By.Id("experience")).SendKeys("7");
            driver.FindElement(By.Id("experience")).SendKeys("8");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
        }
        [Test]
        public void insuranceQuote9ExperienceomittedwithallremainingfieldswithvaliddataAge45Accidents0()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("wsedrftg");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("awsedrfg");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("sedfg");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("awsedrftg");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("wsedrftg@esdfg.com");
            driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(1) > label")).Click();
            driver.FindElement(By.Id("age")).SendKeys("45");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                var element = driver.FindElement(By.Id("btnSubmit"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
        }
        [Test]
        public void insuranceQuote10NoInsuranceDueToAccidents()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("tdrdt");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("esrdtfy");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("esrdtfg");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("werdtf");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("sdfgha@cfvg.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("40");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("6");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("3");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
            }
        }
        [Test]
        public void insuranceQuote11BaseRateForNoExperience()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("erdtfg");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("sedfg");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("essdrfgvhbj");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("sdrfgvhbj");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("SEDRFTG@fgh.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("22");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("0");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$7000"));
            }
        }
        [Test]
        public void insuranceQuote12RateReductionForAgeAndExperience()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("retyg");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("dfcgv");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("sdfgvh");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("rtcygvh");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.CssSelector(".col-md-2 > label")).Click();
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("QWER@dfg.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("16");
            driver.FindElement(By.Id("age")).SendKeys("17");
            driver.FindElement(By.Id("age")).SendKeys("18");
            driver.FindElement(By.Id("age")).SendKeys("19");
            driver.FindElement(By.Id("age")).SendKeys("20");
            driver.FindElement(By.Id("age")).SendKeys("21");
            driver.FindElement(By.Id("age")).SendKeys("22");
            driver.FindElement(By.Id("age")).SendKeys("23");
            driver.FindElement(By.Id("age")).SendKeys("24");
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("age")).SendKeys("26");
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("age")).SendKeys("28");
            driver.FindElement(By.Id("age")).SendKeys("29");
            driver.FindElement(By.Id("age")).SendKeys("30");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("experience")).SendKeys("2");
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("experience")).SendKeys("0");
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("experience")).SendKeys("2");
            driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(2) > label")).Click();
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("1");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.CssSelector(".form-group:nth-child(4) > label")).Click();
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$3905"));
            }
        }
        [Test]
        public void insuranceQuote13BaseRateForLessThanTwoYearsExperience()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("restdgfh");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("rdtfcvg");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("rdtfyghj");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("srdtfyg");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("asdfg@xdcfgv.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(2)")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$5500"));
            }
        }
        [Test]
        public void insuranceQuote14RateReductionForAgeAndExperience()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.CssSelector(".card:nth-child(1) > div > .form-group:nth-child(1)")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("hgjjk");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("ddfgh");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("fgh");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("redtrtfgy");
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.CssSelector(".col-md-4:nth-child(1)")).Click();
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("asdfg@dfg.c0m");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("16");
            driver.FindElement(By.Id("age")).SendKeys("17");
            driver.FindElement(By.Id("age")).SendKeys("18");
            driver.FindElement(By.Id("age")).SendKeys("19");
            driver.FindElement(By.Id("age")).SendKeys("20");
            driver.FindElement(By.Id("age")).SendKeys("21");
            driver.FindElement(By.Id("age")).SendKeys("22");
            driver.FindElement(By.Id("age")).SendKeys("23");
            driver.FindElement(By.Id("age")).SendKeys("24");
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("age")).SendKeys("26");
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("age")).SendKeys("28");
            driver.FindElement(By.Id("age")).SendKeys("29");
            driver.FindElement(By.Id("age")).SendKeys("30");
            driver.FindElement(By.Id("age")).SendKeys("31");
            driver.FindElement(By.Id("age")).SendKeys("32");
            driver.FindElement(By.Id("age")).SendKeys("33");
            driver.FindElement(By.Id("age")).SendKeys("34");
            driver.FindElement(By.Id("age")).SendKeys("35");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("experience")).SendKeys("2");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("experience")).SendKeys("4");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("1");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$3905"));
            }
        }
        [Test]
        public void insuranceQuote15BaseRateForOverAgeLimitExperience()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 672);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("ssdfg");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("sdfg");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("ertygu");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("esdfhgj");
            driver.FindElement(By.CssSelector(".col-md-2")).Click();
            driver.FindElement(By.Id("postalCode")).Click();
            driver.FindElement(By.Id("postalCode")).SendKeys("N2V 1M3");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("asdfg@sdfg.com");
            driver.FindElement(By.Id("age")).Click();
            driver.FindElement(By.Id("age")).SendKeys("16");
            driver.FindElement(By.Id("age")).SendKeys("17");
            driver.FindElement(By.Id("age")).SendKeys("18");
            driver.FindElement(By.Id("age")).SendKeys("19");
            driver.FindElement(By.Id("age")).SendKeys("20");
            driver.FindElement(By.Id("age")).SendKeys("21");
            driver.FindElement(By.Id("age")).SendKeys("22");
            driver.FindElement(By.Id("age")).SendKeys("23");
            driver.FindElement(By.Id("age")).SendKeys("24");
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("age")).SendKeys("26");
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("age")).SendKeys("28");
            driver.FindElement(By.Id("age")).SendKeys("29");
            driver.FindElement(By.Id("age")).SendKeys("30");
            driver.FindElement(By.Id("age")).SendKeys("31");
            driver.FindElement(By.Id("age")).SendKeys("32");
            driver.FindElement(By.Id("age")).SendKeys("33");
            driver.FindElement(By.Id("age")).SendKeys("34");
            driver.FindElement(By.Id("age")).SendKeys("35");
            driver.FindElement(By.Id("age")).SendKeys("36");
            driver.FindElement(By.Id("age")).SendKeys("37");
            driver.FindElement(By.Id("age")).SendKeys("38");
            driver.FindElement(By.Id("age")).SendKeys("39");
            driver.FindElement(By.Id("age")).SendKeys("40");
            driver.FindElement(By.Id("age")).SendKeys("41");
            driver.FindElement(By.Id("age")).SendKeys("42");
            driver.FindElement(By.Id("age")).SendKeys("43");
            driver.FindElement(By.Id("age")).SendKeys("44");
            driver.FindElement(By.Id("age")).SendKeys("45");
            driver.FindElement(By.Id("age")).SendKeys("46");
            driver.FindElement(By.Id("age")).SendKeys("47");
            driver.FindElement(By.Id("age")).SendKeys("48");
            driver.FindElement(By.Id("age")).SendKeys("49");
            driver.FindElement(By.Id("age")).SendKeys("50");
            driver.FindElement(By.Id("age")).SendKeys("51");
            driver.FindElement(By.Id("age")).SendKeys("52");
            driver.FindElement(By.Id("age")).SendKeys("53");
            driver.FindElement(By.Id("age")).SendKeys("54");
            driver.FindElement(By.Id("age")).SendKeys("55");
            driver.FindElement(By.Id("age")).SendKeys("56");
            driver.FindElement(By.Id("age")).SendKeys("57");
            driver.FindElement(By.Id("age")).SendKeys("58");
            driver.FindElement(By.Id("age")).SendKeys("59");
            driver.FindElement(By.Id("age")).SendKeys("60");
            driver.FindElement(By.Id("age")).SendKeys("61");
            driver.FindElement(By.Id("age")).SendKeys("62");
            driver.FindElement(By.Id("age")).SendKeys("63");
            driver.FindElement(By.Id("age")).SendKeys("64");
            driver.FindElement(By.Id("age")).SendKeys("65");
            driver.FindElement(By.Id("age")).SendKeys("66");
            driver.FindElement(By.Id("age")).SendKeys("67");
            driver.FindElement(By.Id("age")).SendKeys("68");
            driver.FindElement(By.Id("age")).SendKeys("69");
            driver.FindElement(By.Id("age")).SendKeys("70");
            driver.FindElement(By.Id("experience")).Click();
            driver.FindElement(By.Id("experience")).SendKeys("1");
            driver.FindElement(By.Id("experience")).SendKeys("2");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("experience")).SendKeys("4");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("experience")).SendKeys("6");
            driver.FindElement(By.Id("experience")).SendKeys("7");
            driver.FindElement(By.Id("experience")).SendKeys("8");
            driver.FindElement(By.Id("experience")).SendKeys("9");
            driver.FindElement(By.Id("experience")).SendKeys("10");
            driver.FindElement(By.Id("experience")).SendKeys("11");
            driver.FindElement(By.Id("experience")).SendKeys("12");
            driver.FindElement(By.Id("experience")).SendKeys("13");
            driver.FindElement(By.Id("experience")).SendKeys("14");
            driver.FindElement(By.Id("experience")).SendKeys("15");
            driver.FindElement(By.Id("experience")).SendKeys("16");
            driver.FindElement(By.Id("experience")).SendKeys("17");
            driver.FindElement(By.Id("experience")).SendKeys("18");
            driver.FindElement(By.Id("experience")).SendKeys("19");
            driver.FindElement(By.Id("experience")).SendKeys("20");
            driver.FindElement(By.Id("experience")).SendKeys("21");
            driver.FindElement(By.Id("experience")).SendKeys("22");
            driver.FindElement(By.Id("experience")).SendKeys("23");
            driver.FindElement(By.Id("experience")).SendKeys("24");
            driver.FindElement(By.Id("experience")).SendKeys("25");
            driver.FindElement(By.Id("experience")).SendKeys("26");
            driver.FindElement(By.Id("experience")).SendKeys("27");
            driver.FindElement(By.Id("experience")).SendKeys("28");
            driver.FindElement(By.Id("experience")).SendKeys("29");
            driver.FindElement(By.Id("experience")).SendKeys("30");
            driver.FindElement(By.Id("experience")).SendKeys("31");
            driver.FindElement(By.Id("experience")).SendKeys("32");
            driver.FindElement(By.Id("experience")).SendKeys("33");
            driver.FindElement(By.Id("experience")).SendKeys("34");
            driver.FindElement(By.Id("experience")).SendKeys("35");
            driver.FindElement(By.Id("experience")).SendKeys("36");
            driver.FindElement(By.Id("experience")).SendKeys("37");
            driver.FindElement(By.Id("experience")).SendKeys("38");
            driver.FindElement(By.Id("experience")).SendKeys("39");
            driver.FindElement(By.Id("experience")).SendKeys("40");
            driver.FindElement(By.Id("experience")).SendKeys("41");
            driver.FindElement(By.Id("experience")).SendKeys("42");
            driver.FindElement(By.Id("experience")).SendKeys("43");
            driver.FindElement(By.Id("experience")).SendKeys("44");
            driver.FindElement(By.Id("experience")).SendKeys("45");
            driver.FindElement(By.Id("experience")).SendKeys("46");
            driver.FindElement(By.Id("experience")).SendKeys("47");
            driver.FindElement(By.Id("experience")).SendKeys("48");
            driver.FindElement(By.Id("experience")).SendKeys("49");
            driver.FindElement(By.Id("experience")).SendKeys("50");
            driver.FindElement(By.Id("accidents")).Click();
            driver.FindElement(By.Id("accidents")).SendKeys("1");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$2840"));
            }
        }
    }
};
